/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import static Customer.Customer_Login.loggedUserID;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vayshalini
 */
public class Customer_Bookingpage extends javax.swing.JFrame {

    public static int journeyid;

    public Customer_Bookingpage() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_lbl = new javax.swing.JLabel();
        heading_lbl = new javax.swing.JLabel();
        motto_lbl = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        combo_pckgtype = new javax.swing.JComboBox<>();
        txt_pckgeprice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_display = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo_packgeid = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_finalprize = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/logo5resize2.jpg"))); // NOI18N
        getContentPane().add(logo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 80));

        heading_lbl.setFont(new java.awt.Font("Buxton Sketch", 1, 62)); // NOI18N
        heading_lbl.setForeground(new java.awt.Color(255, 255, 255));
        heading_lbl.setText("Europe Bus");
        getContentPane().add(heading_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 320, 80));

        motto_lbl.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        motto_lbl.setForeground(new java.awt.Color(204, 255, 204));
        motto_lbl.setText("A tour to be remembered . . .");
        getContentPane().add(motto_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 220, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/download (1).jpg"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 40, 260, 180));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/download.jpg"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 220, 260, 180));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/images (3).jpg"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 400, 260, 180));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/images (1).jpg"))); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 580, 260, 180));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/images (6).jpg"))); // NOI18N
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 760, 260, 180));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/hellopp.jpg"))); // NOI18N
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 300, 620));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/new3.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 760, 260, 180));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/neww.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 760, 260, 180));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/images (5).jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 760, 280, 180));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/new4.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 760, -1, 180));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/new5.jpg"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 760, 260, 180));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/new.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 760, 260, 180));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/images (6).jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 760, 260, 180));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 20, 560));

        combo_pckgtype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_pckgtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Journey", "Return Journey" }));
        getContentPane().add(combo_pckgtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 260, 40));

        txt_pckgeprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_pckgeprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 200, 280, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 69, 69));
        jLabel1.setText("Journey Type");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 140, 40));

        btn_display.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_display.setText("Display Price Amount");
        btn_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_displayActionPerformed(evt);
            }
        });
        getContentPane().add(btn_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 360, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(7, 69, 69));
        jLabel3.setText("Price Of Your Package");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 200, 160, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 69, 69));
        jLabel4.setText("Total Payement");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, 160, 40));

        combo_packgeid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_packgeid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PK0001", "PK0002", "PK0003", "PK0004", "PK0005", "PK0006", "PK0007", "PK0008", "PK0009", "PK00010", "PK00011", "PK00012", " " }));
        getContentPane().add(combo_packgeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 260, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(7, 69, 69));
        jLabel6.setText("Select Your Package ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 160, 40));

        txt_finalprize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_finalprize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 320, 280, 40));

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("We don't offer overbooking for trips");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 420, 60));

        jLabel7.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("For your Attention");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(7, 69, 69));
        jLabel8.setText("After clarifying the your details we will mail you the confirmation, and payment method");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 600, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 69, 69));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/cus1n.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 1240, 600));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/new234567.jpg"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_displayActionPerformed
        String packageid = combo_packgeid.getSelectedItem().toString();
        int packagetype = combo_pckgtype.getSelectedIndex();

        try {
            Connection con = DataBaseConnection.DataBaseConnectionClass.createDBConnection();
            ResultSet ps = con.createStatement().executeQuery("Select * from journeyinfo");
            while (ps.next()) {

                String dbpackageid = ps.getString("PackageID");
                String dbprice = ps.getString("JourneyPrice");
                if (packageid.equals(dbpackageid)) {

                    txt_pckgeprice.setText(dbprice);
                    
                }

                if (packagetype == 0) {
                     txt_finalprize.setText(dbprice);
                }else if(packagetype ==1){
                    txt_finalprize.setText("You should pay in double");
                }

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btn_displayActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {

         /* Set the Nimbus look and feel */
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
          */
         try {
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 if ("Nimbus".equals(info.getName())) {
                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
                     break;
                 }
             }
         } catch (ClassNotFoundException ex) {
             java.util.logging.Logger.getLogger(Customer_Bookingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
             java.util.logging.Logger.getLogger(Customer_Bookingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
             java.util.logging.Logger.getLogger(Customer_Bookingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
             java.util.logging.Logger.getLogger(Customer_Bookingpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }
         //</editor-fold>

         /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                 new Customer_Bookingpage().setVisible(true);
             }
         });
     }
     
     


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_display;
    private javax.swing.JComboBox<String> combo_packgeid;
    private javax.swing.JComboBox<String> combo_pckgtype;
    private javax.swing.JLabel heading_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo_lbl;
    private javax.swing.JLabel motto_lbl;
    private javax.swing.JTextField txt_finalprize;
    private javax.swing.JTextField txt_pckgeprice;
    // End of variables declaration//GEN-END:variables
}
