/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import static Employee.Employee_Interface.journeyid;
import Customer.Customer_Bookingpage;
import Employee.Employee_Interface;
import Employee.Emplyee_aLogin;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vayshalini
 */
 public class CustomerVisitPackages_FirstIntrfc extends javax.swing.JFrame {
    public static int selectedrow;
    
    public CustomerVisitPackages_FirstIntrfc() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_lbl = new javax.swing.JLabel();
        heading_lbl = new javax.swing.JLabel();
        motto_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSearchdes_dep = new javax.swing.JTextField();
        srch_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_booknow = new javax.swing.JButton();
        view_alldetails = new javax.swing.JTabbedPane();
        viewpackage = new javax.swing.JScrollPane();
        customer_table = new javax.swing.JTable();
        Customer_Overview = new javax.swing.JInternalFrame();
        txt_dep = new javax.swing.JTextField();
        txt_deptime = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        itinerary_box = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_pkgIDadd = new javax.swing.JTextField();
        txt_des = new javax.swing.JTextField();
        txt_dur = new javax.swing.JTextField();
        txt_type = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_cap = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        viewdetails_btn = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        Customer_Register = new javax.swing.JInternalFrame();
        txt_lname = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        txt_contactnum = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn_clearall = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        combo_gender = new javax.swing.JComboBox<>();
        txt_pswrd = new javax.swing.JPasswordField();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/logo5resize2.jpg"))); // NOI18N
        getContentPane().add(logo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 80));

        heading_lbl.setFont(new java.awt.Font("Buxton Sketch", 1, 62)); // NOI18N
        heading_lbl.setForeground(new java.awt.Color(255, 255, 255));
        heading_lbl.setText("Europe Bus");
        getContentPane().add(heading_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 320, 80));

        motto_lbl.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        motto_lbl.setForeground(new java.awt.Color(204, 255, 204));
        motto_lbl.setText("A tour to be remembered . . .");
        getContentPane().add(motto_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 220, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/download.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 220, 260, 180));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/images (1).jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 580, 260, 180));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/download (1).jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 40, 260, 180));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/images (6).jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 760, 260, 180));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/images (3).jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 400, 260, 180));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/images (5).jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 760, 280, 180));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/new.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 760, 260, 180));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/neww.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 760, 260, 180));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/new4.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 760, -1, 180));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/new5.jpg"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 760, 260, 180));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Search by Departure or Destination");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 260, 40));

        txtSearchdes_dep.setBorder(null);
        txtSearchdes_dep.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtSearchdes_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchdes_depActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearchdes_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 280, 40));

        srch_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/searchmeplzz.jpg"))); // NOI18N
        srch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch_btnActionPerformed(evt);
            }
        });
        getContentPane().add(srch_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 100, 40, 40));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Want to discover the best of Europe? You are in the right place.  ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 560, 20));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("the best family destinations, the most romantic destinations,  the hidden gems or the best fairytale destinations and many more.  ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1100, 40));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("There is so much to discover in Europe!");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 400, 60));

        btn_booknow.setBackground(new java.awt.Color(204, 204, 204));
        btn_booknow.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btn_booknow.setForeground(new java.awt.Color(21, 79, 129));
        btn_booknow.setText("BOOK NOW");
        btn_booknow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_booknowActionPerformed(evt);
            }
        });
        getContentPane().add(btn_booknow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 80, 160, 60));

        view_alldetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        view_alldetails.setForeground(new java.awt.Color(22, 69, 145));
        view_alldetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        view_alldetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_alldetailsMouseClicked(evt);
            }
        });

        customer_table.setAutoCreateRowSorter(true);
        customer_table.setBackground(new java.awt.Color(204, 255, 204));
        customer_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        customer_table.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        customer_table.setForeground(new java.awt.Color(0, 102, 51));
        customer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Package ID", "Departure Country & Town", "Destination Country & Town", "Duration", "Tour Type", "Depature Time", "Journey Price", "Capacity", "Itinerary"
            }
        ));
        customer_table.setFocusable(false);
        customer_table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        customer_table.setRowHeight(25);
        customer_table.setSelectionBackground(new java.awt.Color(204, 255, 255));
        customer_table.setSelectionForeground(new java.awt.Color(0, 0, 102));
        customer_table.getTableHeader().setReorderingAllowed(false);
        customer_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_tableMouseClicked(evt);
            }
        });
        viewpackage.setViewportView(customer_table);

        view_alldetails.addTab("View Packages", viewpackage);

        Customer_Overview.setVisible(true);
        Customer_Overview.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_dep.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        Customer_Overview.getContentPane().add(txt_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 240, 40));

        txt_deptime.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        Customer_Overview.getContentPane().add(txt_deptime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 240, 40));

        itinerary_box.setColumns(20);
        itinerary_box.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        itinerary_box.setRows(5);
        jScrollPane3.setViewportView(itinerary_box);

        Customer_Overview.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 660, 240));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(22, 69, 145));
        jLabel12.setText("Journey Price (Rs.)");
        Customer_Overview.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, 40));

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(22, 69, 145));
        jLabel13.setText("Departure Country & Town");
        Customer_Overview.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 340, 40));

        jLabel19.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(22, 69, 145));
        jLabel19.setText("Destination Country & Town");
        Customer_Overview.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 340, 40));

        jLabel21.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(22, 69, 145));
        jLabel21.setText("Departure Time");
        Customer_Overview.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 200, 40));

        jLabel22.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(22, 69, 145));
        jLabel22.setText("Capacity");
        Customer_Overview.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 100, 40));

        jLabel23.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(22, 69, 145));
        jLabel23.setText("Itinerary");
        Customer_Overview.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 20));

        jLabel24.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(22, 69, 145));
        jLabel24.setText("Package ID");
        Customer_Overview.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 140, 40));

        jLabel25.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(22, 69, 145));
        jLabel25.setText("Tour Type");
        Customer_Overview.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 120, 40));

        jLabel26.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(22, 69, 145));
        jLabel26.setText("Duration");
        Customer_Overview.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 120, 40));

        txt_pkgIDadd.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        txt_pkgIDadd.setToolTipText("");
        txt_pkgIDadd.setName(""); // NOI18N
        Customer_Overview.getContentPane().add(txt_pkgIDadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 200, 40));

        txt_des.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        Customer_Overview.getContentPane().add(txt_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 360, 240, 40));

        txt_dur.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        Customer_Overview.getContentPane().add(txt_dur, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 160, 40));

        txt_type.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        Customer_Overview.getContentPane().add(txt_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 440, 180, 40));

        txt_price.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        txt_price.setToolTipText("Per Person");
        Customer_Overview.getContentPane().add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 180, 40));

        txt_cap.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        Customer_Overview.getContentPane().add(txt_cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 120, 40));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/overview3.jpg"))); // NOI18N
        Customer_Overview.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 160, 220));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/overview1.jpg"))); // NOI18N
        Customer_Overview.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 220, 140));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/overview.jpg"))); // NOI18N
        Customer_Overview.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 140, 280, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Please Remember the Package ID to book");
        Customer_Overview.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, -1, -1));

        viewdetails_btn.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        viewdetails_btn.setText("View the Selected Package");
        viewdetails_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetails_btnActionPerformed(evt);
            }
        });
        Customer_Overview.getContentPane().add(viewdetails_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        jLabel30.setFont(new java.awt.Font("Yu Gothic Medium", 0, 16)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/cs7gtnewww.jpg"))); // NOI18N
        Customer_Overview.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 1560, 560));

        view_alldetails.addTab("Overview", Customer_Overview);

        Customer_Register.setVisible(true);
        Customer_Register.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Customer_Register.getContentPane().add(txt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 360, 40));

        jLabel31.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel31.setText("First Name");
        Customer_Register.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel32.setText("Last Name");
        Customer_Register.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel33.setText("Gender");
        Customer_Register.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel34.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel34.setText("Date of Birth");
        Customer_Register.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        jLabel35.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel35.setText("Contact No");
        Customer_Register.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, -1, -1));

        jLabel36.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel36.setText("Address");
        Customer_Register.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, -1, -1));

        jLabel37.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel37.setText("E-mail");
        Customer_Register.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel38.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel38.setText("Password");
        Customer_Register.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        txt_dob.setToolTipText("DD/MM/YYYY");
        Customer_Register.getContentPane().add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 360, 40));
        txt_dob.getAccessibleContext().setAccessibleName("DD/MM/YYYY");

        Customer_Register.getContentPane().add(txt_contactnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 80, 340, 40));

        txt_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mailActionPerformed(evt);
            }
        });
        Customer_Register.getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 380, 40));
        Customer_Register.getContentPane().add(txt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 380, 40));

        jCheckBox1.setBackground(new java.awt.Color(216, 237, 237));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("Click here to indicate that you have read and agree to the terms presented in the Terms and Conditions agreement");
        Customer_Register.getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        btn_clearall.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_clearall.setText("CLEAR ALL");
        btn_clearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearallActionPerformed(evt);
            }
        });
        Customer_Register.getContentPane().add(btn_clearall, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 440, 120, 40));

        btn_register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_register.setText("REGISTER");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        Customer_Register.getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 440, 120, 40));

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane4.setViewportView(txt_address);

        Customer_Register.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 180, 340, 140));

        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        Customer_Register.getContentPane().add(combo_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 40));
        Customer_Register.getContentPane().add(txt_pswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 280, 40));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/clickmeee.jpg"))); // NOI18N
        Customer_Register.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1520, 720));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Customer_Register.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -120, 620, -1));

        view_alldetails.addTab("Register to Book", Customer_Register);

        getContentPane().add(view_alldetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 1500, 600));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/new3.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 760, 260, 180));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/cs7rnwwww.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch_btnActionPerformed
     
        String searchtext = txtSearchdes_dep.getText();
       
            try {
                Connection con = DataBaseConnection.DataBaseConnectionClass.createDBConnection();

                ResultSet rstasks = con.createStatement().executeQuery("select * from journeyinfo where DepartureTown LIKE '%" + searchtext + "%' || DestinationTown LIKE '%" + searchtext + "%'");

                DefaultTableModel dtm = (DefaultTableModel) customer_table.getModel();
                dtm.setRowCount(0);
               

                while (rstasks.next()) {
                    journeyid = rstasks.getInt("idjourneyinfo");

                    Vector<String> vecDate = new Vector<>();

                    vecDate.add(rstasks.getString("PackageID"));
                    vecDate.add(rstasks.getString("DepartureTown"));
                    vecDate.add(rstasks.getString("DestinationTown"));
                    vecDate.add(rstasks.getString("Duration"));
                    vecDate.add(rstasks.getString("TourType"));
                    vecDate.add(rstasks.getString("DepartureTime"));
                    vecDate.add(rstasks.getString("JourneyPrice"));
                    vecDate.add(rstasks.getString("Capacity"));
                    vecDate.add(rstasks.getString("Itinerary"));

                    dtm.addRow(vecDate);

                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        

    }//GEN-LAST:event_srch_btnActionPerformed

    private void txtSearchdes_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchdes_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchdes_depActionPerformed

    private void btn_booknowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_booknowActionPerformed
       new Customer_Login().setVisible(true);
     
    }//GEN-LAST:event_btn_booknowActionPerformed

    private void view_alldetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_alldetailsMouseClicked

    }//GEN-LAST:event_view_alldetailsMouseClicked

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        String FsName = txt_fname.getText();
        String LsName = txt_lname.getText();
        String Gender = combo_gender.getSelectedItem().toString();
        String Contact = txt_contactnum.getText();
        String dob = txt_dob.getText();
        String address = txt_address.getText();
        String email = txt_mail.getText();
        String password = txt_pswrd.getText();

        if (FsName.equals("") || LsName.equals("") || Contact.equals("") || dob.equals("") || address.equals("") || email.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(
                rootPane,
                "No values entered",
                "Error",
                JOptionPane.ERROR_MESSAGE);

        } else {

            try {

                int insertcount = registerCustomer(FsName, LsName, Gender, Contact, dob, address, email, password);

                if (insertcount < 10) {
                    JOptionPane.showMessageDialog(
                        rootPane,
                        "Registration Successful",
                        "Success",
                        JOptionPane.PLAIN_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(
                        rootPane,
                        "Save Registration Failed",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);

                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_clearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearallActionPerformed

        txt_pkgIDadd.setText("");
        txt_dep.setText("");
        txt_des.setText("");
        txt_dur.setText("");
        txt_type.setText("");
        txt_deptime.setText("");
        txt_price.setText("");
        txt_cap.setText("");
        itinerary_box.setText("");

    }//GEN-LAST:event_btn_clearallActionPerformed

    private void txt_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mailActionPerformed

    private void customer_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_tableMouseClicked

    }//GEN-LAST:event_customer_tableMouseClicked

    private void viewdetails_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetails_btnActionPerformed
         int i = customer_table.getSelectedRow();

        DefaultTableModel dtm = (DefaultTableModel) customer_table.getModel();
        String packageid = dtm.getValueAt(i, 0).toString();
        String deptown = dtm.getValueAt(i, 1).toString();
        String destown = dtm.getValueAt(i, 2).toString();
        String duration = dtm.getValueAt(i, 3).toString();
        String tourtype = dtm.getValueAt(i, 4).toString();
        String deptime = dtm.getValueAt(i, 5).toString();
        String price = dtm.getValueAt(i, 6).toString();
        String capacity = dtm.getValueAt(i, 7).toString();
        String itinerary = dtm.getValueAt(i, 8).toString();
       

        fillFields(packageid, deptown, destown, duration, tourtype, deptime, price, capacity, itinerary);
              
    }//GEN-LAST:event_viewdetails_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerVisitPackages_FirstIntrfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerVisitPackages_FirstIntrfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerVisitPackages_FirstIntrfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerVisitPackages_FirstIntrfc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerVisitPackages_FirstIntrfc().setVisible(true);
}
        });
}
    
  private void fillFields(String packageid, String deptown, String destown, String duration, String tourtype, String deptime, String price, String capacity, String itinerary) {

       txt_pkgIDadd.setText(packageid);
       txt_dep.setText(deptown);
       txt_des.setText(destown);
       txt_dur.setText(duration);
       txt_type.setText(tourtype);
       txt_deptime.setText(deptime);
       txt_price.setText(price);
       txt_cap.setText(capacity);
       itinerary_box.setText(itinerary);
   
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Customer_Overview;
    private javax.swing.JInternalFrame Customer_Register;
    private javax.swing.JButton btn_booknow;
    private javax.swing.JButton btn_clearall;
    private javax.swing.JButton btn_register;
    private javax.swing.JComboBox<String> combo_gender;
    private javax.swing.JTable customer_table;
    private javax.swing.JLabel heading_lbl;
    private javax.swing.JTextArea itinerary_box;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logo_lbl;
    private javax.swing.JLabel motto_lbl;
    private javax.swing.JButton srch_btn;
    private javax.swing.JTextField txtSearchdes_dep;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_cap;
    private javax.swing.JTextField txt_contactnum;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_deptime;
    private javax.swing.JTextField txt_des;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_dur;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_pkgIDadd;
    private javax.swing.JTextField txt_price;
    private javax.swing.JPasswordField txt_pswrd;
    private javax.swing.JTextField txt_type;
    private javax.swing.JTabbedPane view_alldetails;
    private javax.swing.JButton viewdetails_btn;
    private javax.swing.JScrollPane viewpackage;
    // End of variables declaration//GEN-END:variables

    private int registerCustomer(String FsName, String LsName, String Gender, String Contact, String dob, String address, String email, String password) {
       try {
            Connection nwcon = DataBaseConnection.DataBaseConnectionClass.createDBConnection();                                                                                                 
            int recordcount = nwcon.createStatement().executeUpdate("insert into customertable(FirstName,LastName,Gender,ContactNo,DateOfBirth,Address,Email,Password) values('" + FsName + "','" + LsName + "','" + Gender + "','" + Contact + "','" + dob + "','" + address + "','" + email + "','" + password + "')");

            return recordcount;

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Couldn't input values! Retry",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return 0;
        }
    }

}