/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import Employee.Employee_Interface;
import static Employee.Emplyee_aLogin.loggedUserID;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Vayshalini
 */
public class Customer_Login extends javax.swing.JFrame {

    public static int loggedUserID;
    int loginstatus = 0;

    public Customer_Login() {
        initComponents();
        enterusrnm_lbl.setVisible(false);
         this.setLocation(this.getWidth() / 1, this.getHeight() / 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusrnm = new javax.swing.JTextField();
        txtpswrd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        exit_btn = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        enterusrnm_lbl = new javax.swing.JLabel();
        reset_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/logo5resize2.jpg"))); // NOI18N
        getContentPane().add(logo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("User Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 40));

        txtusrnm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusrnmKeyTyped(evt);
            }
        });
        getContentPane().add(txtusrnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 300, 40));

        txtpswrd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpswrdKeyTyped(evt);
            }
        });
        getContentPane().add(txtpswrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 300, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel3.setText("(Enter your email )");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 160, 40));

        exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/1471180807_Close_Box_Red.png"))); // NOI18N
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 20, 20));

        btn_login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 120, 40));

        enterusrnm_lbl.setForeground(new java.awt.Color(102, 102, 102));
        enterusrnm_lbl.setText("User Name is empty");
        getContentPane().add(enterusrnm_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 140, -1));

        reset_btn.setBackground(new java.awt.Color(204, 204, 204));
        reset_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/hayyo.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 660, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
       this.dispose();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String username = txtusrnm.getText();
        String password = txtpswrd.getText();

        if (username.equals("") && password.equals("")) {
             JOptionPane.showMessageDialog(rootPane, "Enter username & password", "Login Error", JOptionPane.CANCEL_OPTION);
        } else if (username.equals("") && !password.equals("")) {
             JOptionPane.showMessageDialog(rootPane, "Please enter the username", "Login Error", JOptionPane.ERROR_MESSAGE);
        } else if (!username.equals("") && password.equals("")) {
             JOptionPane.showMessageDialog(rootPane, "Please enter the password", "Login Error", JOptionPane.ERROR_MESSAGE);
        } else {
            
            try {
                Connection con = DataBaseConnection.DataBaseConnectionClass.createDBConnection();
                ResultSet ps = con.createStatement().executeQuery("Select * from customertable");
                while (ps.next()) {

                    String dbusername = ps.getString("Email");
                    String dbpassword = ps.getString("Password");

                    if (username.equals(dbusername) && password.equals(dbpassword)) {

                        loggedUserID = ps.getInt("idcustomertable");
                        loginstatus = 1;
                        
                        new Customer_Bookingpage().setVisible(true);
                        this.dispose();

                        break;

                    }
                }

                if (loginstatus == 0) {
                    JOptionPane.showMessageDialog(
                            rootPane,
                            "Haven't you registered? Then go back to Main Page & Register an account.",
                            "Login Error",
                            JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }


    }//GEN-LAST:event_btn_loginActionPerformed

    private void txtusrnmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusrnmKeyTyped
      enterusrnm_lbl.setVisible(false);
    }//GEN-LAST:event_txtusrnmKeyTyped

    private void txtpswrdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpswrdKeyTyped
        enterusrnm_lbl.setVisible(false);
    }//GEN-LAST:event_txtpswrdKeyTyped

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        txtusrnm.setText(""); //set empty text
        txtpswrd.setText(""); // set empty text
    }//GEN-LAST:event_reset_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel enterusrnm_lbl;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logo_lbl;
    private javax.swing.JButton reset_btn;
    private javax.swing.JPasswordField txtpswrd;
    private javax.swing.JTextField txtusrnm;
    // End of variables declaration//GEN-END:variables
}
