/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vayshalini
 */
public class Emplyee_aLogin extends javax.swing.JFrame {
    
    public static int loggedUserID;
    int loginstatus = 0;
    
    public Emplyee_aLogin() {
        initComponents();
        enterusrnm_lbl.setVisible(false);
        this.setLocation(this.getWidth() / 1, this.getHeight() / 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        logo_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        exit_btn = new javax.swing.JButton();
        enterusrnm_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        background_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(13, 99, 166));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_btn.setBackground(new java.awt.Color(204, 204, 204));
        login_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 120, 40));

        reset_btn.setBackground(new java.awt.Color(204, 204, 204));
        reset_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        getContentPane().add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 120, 40));

        logo_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/logo5resize2.jpg"))); // NOI18N
        getContentPane().add(logo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 153));
        jLabel1.setText("Employee User ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 153));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 80));

        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 240, 40));

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordKeyTyped(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 240, 40));

        exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/1471180807_Close_Box_Red.png"))); // NOI18N
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 20, 20));

        enterusrnm_lbl.setForeground(new java.awt.Color(255, 204, 204));
        enterusrnm_lbl.setText("UserID is empty");
        getContentPane().add(enterusrnm_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 140, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 100, 40));

        background_lbl.setBackground(new java.awt.Color(28, 34, 131));
        background_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_Folder/loginpagebackground___agg.png"))); // NOI18N
        getContentPane().add(background_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        txtusername.setText(""); //set empty text
        txtpassword.setText(""); // set empty text
    }//GEN-LAST:event_reset_btnActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        String username = txtusername.getText();
        String password = txtpassword.getText();
        
        if (username.equals("") && password.equals("")) {
            
            JOptionPane.showMessageDialog(rootPane, "Enter username & password", "Login Error", JOptionPane.CANCEL_OPTION);
            
        } else if (username.equals("") && !password.equals("")) {
            
            JOptionPane.showMessageDialog(rootPane, "Please enter the username", "Login Error", JOptionPane.ERROR_MESSAGE);
        } else if (!username.equals("") && password.equals("")) {
            
            JOptionPane.showMessageDialog(rootPane, "Please enter the password", "Login Error", JOptionPane.ERROR_MESSAGE);
            
        } else {
            try {
                Connection con = DataBaseConnection.DataBaseConnectionClass.createDBConnection();
                //to get the user username and password
                ResultSet ps = con.createStatement().executeQuery("Select * from employeedetails");
                //itrrate through all records
                while (ps.next()) {
                    //dbusername , dbpassword = local variable
                    String dbusername = ps.getString("UserID");
                    String dbpassword = ps.getString("Password");
                    
                    if (username.equals(dbusername) && password.equals(dbpassword)) {
                        
                        loggedUserID = ps.getInt("idemployeedetails");
                        loginstatus = 1;
                        JOptionPane.showMessageDialog(
                                rootPane,
                                "You've Logined successfully",
                                "Successfully Logined",
                                JOptionPane.PLAIN_MESSAGE);
                        new Employee_Interface().setVisible(true);
                        this.dispose();
                        // use break to come out from the loop
                        break;
                        
                    }
                }
                
                if (loginstatus == 0) {
                    JOptionPane.showMessageDialog(
                            rootPane,
                            "Invalid Username and Password. Retry",
                            "Login Error",
                            JOptionPane.ERROR_MESSAGE);
                }
                
                
            } catch (Exception ex) {  //remove sql
                ex.printStackTrace();
            }
        }
        

    }//GEN-LAST:event_login_btnActionPerformed

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        enterusrnm_lbl.setVisible(false);
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyTyped
        if (txtusername.getText().equals("")) {
            enterusrnm_lbl.setVisible(true);
            
        }
    }//GEN-LAST:event_txtpasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emplyee_aLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emplyee_aLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emplyee_aLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emplyee_aLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emplyee_aLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_lbl;
    private javax.swing.JLabel enterusrnm_lbl;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel logo_lbl;
    private javax.swing.JButton reset_btn;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
